version: "2"
services:
  jenkis:
    image: jenkins/jenkins
    hostname: jenkis-01
    # command: sh -c "curl -fsSLO https://download.docker.com/linux/static/edge/x86_64/docker-17.04.0-ce.tgz && tar xzvf docker-17.04.0-ce.tgz && mv docker/docker /usr/local/bin && rm -r docker docker-17.04.0-ce.tgz"
    # wget http://mirror.nbtelecom.com.br/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip && unzip apache-maven-3.6.1-bin.zip && mv apache-maven-3.6.1 /opt && ln -s /opt/apache-maven-3.6.1/bin/mvn /usr/bin/
    links:
      - sonar
    container_name: jenkins
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin:/usr/bin
    #   - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      nettas02:
        ipv4_address: 200.17.20.5

  db:
    image: postgres:9.6.2
    hostname: pgsql-01
    container_name: pgsql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    networks:
      nettas02:
        ipv4_address: 200.17.20.3

  sonar:
    image: sonarqube:6.3.1
    hostname: sonar-01
    container_name: sonar
    links:
      - db
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://pgsql-01:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
    networks:
       nettas02:
        ipv4_address: 200.17.20.4

  nexus:
    image: sonatype/nexus3
    hostname: nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      nettas02:
        ipv4_address: 200.17.20.2

networks:
  nettas02:
    driver: bridge
    ipam:
     config:
       - subnet: 200.17.20.0/16
         gateway: 200.17.20.1
# volumes:
#     jenkins_home:
